const postConstants = {
  FETCH_POSTS_LIST_START: 'FETCH_POSTS_LIST_START',
  FETCH_POSTS_LIST_SUCCESS: 'FETCH_POSTS_LIST_SUCCESS',
  FETCH_POSTS_LIST_FAILURE: 'FETCH_POSTS_LIST_FAILURE',
  CLEAR_SUCCESS_FAILURE: 'CLEAR_SUCCESS_FAILURE',
  FETCH_INDIVIDUAL_POST_START: 'FETCH_INDIVIDUAL_POST_START',
  FETCH_INDIVIDUAL_POST_SUCCESS: 'FETCH_INDIVIDUAL_POST_SUCCESS',
  FETCH_INDIVIDUAL_POST_FAILURE: 'FETCH_INDIVIDUAL_POST_FAILURE',
  ADD_POST_START: 'ADD_POST_START',
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
  ADD_POST_FAILURE: 'ADD_POST_FAILURE',
};

export default postConstants;
