const commentConstants = {
  ADD_COMMENT_START: 'ADD_COMMENT_START',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',
  FETCH_COMMENTS_START: 'FETCH_COMMENTS_START',
  FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
  FETCH_COMMENTS_FAILURE: 'FETCH_COMMENTS_FAILURE',
  CLEAR_SUCCESS_FAILURE: 'CLEAR_SUCCESS_FAILURE',
};

export default commentConstants;
